### ISSUE TITLE
.yaml file path

### ISSUE THREAD

**Issue by jakeown** [GBTAmmoniaSurvey/keystone#15]
The path to the Yaml file in postprocess.py isn't assigned correctly.  I have it linking to the python path, but it looks like the setup.py file doesn't copy the yaml file over to where the python files are imported.  Is there a better way to assign that path? Or should we just copy the yaml file over during setup.py?
https://github.com/GBTAmmoniaSurvey/keystone/blob/master/keystone/postprocess.py#L7-L9

**Comment by low-sky** [comment]
Move to the astropy style repository data folder.

**Comment by low-sky** [comment]
Addressed in #19
